// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJxr7eXH5D29HoM5lkawaCgnJPnxupr_E',
    appId: '1:1038588735855:web:edb48c2729eb2c6344b89a',
    messagingSenderId: '1038588735855',
    projectId: 'gauramarg-firebase',
    authDomain: 'gauramarg-firebase.firebaseapp.com',
    storageBucket: 'gauramarg-firebase.appspot.com',
    measurementId: 'G-VVXRRJ4PS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-iE9DVd6ngodoZ3OZZ91TOIyqeajWCiw',
    appId: '1:1038588735855:android:6d8a414ad69901b144b89a',
    messagingSenderId: '1038588735855',
    projectId: 'gauramarg-firebase',
    storageBucket: 'gauramarg-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0P4MVmGehBDBPEXqjunKBGHyYsa7tyg',
    appId: '1:1038588735855:ios:76de2cc468d1dfad44b89a',
    messagingSenderId: '1038588735855',
    projectId: 'gauramarg-firebase',
    storageBucket: 'gauramarg-firebase.appspot.com',
    iosClientId: '1038588735855-qvt0ekm8gf7s89amtikrc0jtgisgmmu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gauramargMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn0P4MVmGehBDBPEXqjunKBGHyYsa7tyg',
    appId: '1:1038588735855:ios:76de2cc468d1dfad44b89a',
    messagingSenderId: '1038588735855',
    projectId: 'gauramarg-firebase',
    storageBucket: 'gauramarg-firebase.appspot.com',
    iosClientId: '1038588735855-qvt0ekm8gf7s89amtikrc0jtgisgmmu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gauramargMobile',
  );
}
